# Generated by Django 5.1.2 on 2025-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=32)),
                ('datetime', models.TextField()),
                ('date_unix', models.TextField()),
                ('score', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('icon', models.TextField()),
                ('number', models.TextField()),
                ('url', models.TextField()),
                ('position', models.CharField(max_length=32)),
                ('birthday', models.CharField()),
                ('country', models.CharField(max_length=32)),
                ('command', models.CharField(max_length=32)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('season', models.CharField(max_length=32)),
                ('url', models.TextField()),
                ('logo', models.TextField()),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
    ]
