# Generated by Django 5.1.2 on 2025-04-23 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCommands',
            fields=[
                ('command_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('command_staff', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None)),
            ],
        ),
    ]
