# Generated by Django 5.1.2 on 2025-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
