# Generated by Django 5.1.2 on 2025-01-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='null', max_length=254, unique=True),
        ),
    ]
