# Generated by Django 5.1.2 on 2025-01-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
