# Generated by Django 5.1.2 on 2025-04-21 06:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
