# Generated by Django 5.1.2 on 2025-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuserlocalcredentials_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserlocalcredentials',
            name='password',
            field=models.CharField(max_length=18, verbose_name='password'),
        ),
    ]
