# Generated by Django 5.1.2 on 2024-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_user_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refresh_token',
            field=models.TextField(default=None),
        ),
    ]
