# Generated by Django 5.1.2 on 2024-11-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
