# Generated by Django 5.1.2 on 2025-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuserlocalcredentials_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusergooglecredentials',
            name='google_refresh_token',
            field=models.TextField(default=None),
        ),
    ]
