# Generated by Django 5.1.2 on 2025-04-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customusergooglecredentials_google_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusergooglecredentials',
            name='google_refresh_token',
            field=models.TextField(default=None, null=True),
        ),
    ]
