# Generated by Django 5.1.2 on 2025-04-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('users', '0008_alter_customusergooglecredentials_google_refresh_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='customuserlocalcredentials',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuserlocalcredentials',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
