# Generated by Django 5.1.2 on 2025-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertelegramcredentials',
            name='refresh_token',
            field=models.TextField(default=None),
        ),
    ]
