# Generated by Django 5.1.2 on 2025-05-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customusertelegramcredentials_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusertelegramcredentials',
            name='refresh_token',
        ),
    ]
