# Generated by Django 5.1.2 on 2025-01-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserGoogle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=32, unique=True)),
                ('email', models.CharField(default=None, error_messages={'unique': 'A user with that email already exists.'}, max_length=64, unique=True)),
                ('refresh_token', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
