# Generated by Django 5.1.2 on 2025-05-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='password'),
        ),
    ]
