# Generated by Django 5.1.2 on 2025-01-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customusergoogle_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusergoogle',
            name='email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
