# Generated by Django 5.1.2 on 2025-05-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
