# Generated by Django 5.1.2 on 2025-01-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customusergoogle_email_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernames',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customusergoogle'),
        ),
    ]
