# Generated by Django 5.1.2 on 2025-01-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_usernames_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusergoogle',
            name='id',
        ),
        migrations.AlterField(
            model_name='customusergoogle',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Usernames',
        ),
    ]
