# Generated by Django 5.1.2 on 2025-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_customusergoogle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserTelegram',
            fields=[
                ('username', models.CharField(error_messages={'unique': 'A user with that ysername already exists.'}, max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
