# Generated by Django 5.1.2 on 2025-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customusertelegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertelegram',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
