# Generated by Django 5.1.2 on 2025-01-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customusertelegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertelegram',
            name='auth_date',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='customusertelegram',
            name='first_name',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='customusertelegram',
            name='hash',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='customusertelegram',
            name='id',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='customusertelegram',
            name='photo_url',
            field=models.TextField(default=None),
        ),
    ]
