"""
Django settings for belfoot_fantasy project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from . import env

BASE_DIR = Path(__file__).resolve().parent.parent

# Попытка импорта среды переменных. В случае неуспеха будет использована тестовая БД. //TODO ВОЗМОЖНОСТЬ ЗАПИСИ ПЕРЕМЕННЫХ ЧЕРЕЗ CI/CD
try:
    env.set_env()
    SECRET_KEY = os.getenv('SECRET_KEY')
    DATABASES = {
        'default': {
            'ATOMIC_REQUESTS': True,
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('NAME'),
            'USER': os.getenv('USER'),
            'PASSWORD': os.getenv('PASSWORD'),
            'HOST': os.getenv('HOST'),
            'PORT': os.getenv('PORT')
            }

        }

except:
    SECRET_KEY = 'SOME_SECRET_KEY'
    DATABASES = {
        'default': {
            'ATOMIC_REQUESTS': True,
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'test_belfoot_fantasy_db',
            'USER': 'belfoot_root_1_test',
            'PASSWORD': "test",
            'HOST': '127.0.0.1',
            'PORT': '5432'
        }
    }

# Режим разработчика. Выключить при проде
DEBUG = True

# Хосты, которые будет обслуживать фреймворк. //TODO РАССМОТРЕТЬ ВОЗМОЖНОСТЬ ИСПОЛЬЗОВАНИЯ КОНКРЕТНОГО ИМЕНИ ХОСТА
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Здесь хранятся приложения бэкенда. При создании новых добавлять сюда
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'rest_framework'
]

# Промежуточный софт
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Хранилище урлов
ROOT_URLCONF = 'belfoot_fantasy.urls'

# Перечень шаблонов Django
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Указатель WSGI настроек приложений
WSGI_APPLICATION = 'belfoot_fantasy.wsgi.application'

# Валидаторы для паролей
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Модель, используемая для аутентификации.
AUTH_USER_MODEL = 'users.CustomUser'

# Настройка урлов для логина, логаута пользователей и редиректа в случае наличия сессии //TODO ЛИЧНЫЙ КАБИНЕТ
# LOGIN_REDIRECT_URL = '/accounts/profile'
# LOGIN_URL = '/accounts/login/'
# LOGOUT_REDIRECT_URL = '/accounts/logout'
# PASSWORD_RESET_TIMEOUT = 900


# Настройки сессий
SESSION_COOKIE_HTTPONLY = True  # Куки-файл с сессией недоступен для JS скрипта
SESSION_EXPIRE_AT_BROWSER_CLOSE = True    # Сессия закрывается при закрытии браузера
SESSION_FILE_PATH = None    # Файлы, в котором хранятся сессии
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'   # Сериализатор для сессий

#SITE_ID = 'Понадобится в будущем'   # ID сайта в случае, если одна БД обслуживает несколько сайтов

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_COOKIE_HTTPONLY = True # CSRF куки недоступен для JS скрипта
CSRF_TRUSTED_ORIGINS = []   # Доверенные домены, для которых CSRF не нужен

# Отключенные юзерагенты различных парсеров
# DISALLOWED_USER_AGENTS = ['BLEXBot', 'coccocbot-web', 'Baiduspider', 'Cliqzbot', 'SeopultContentAnalyzer',
#                           'serpstatbot', 'LinkpadBot', 'DataForSeoBot', 'Scrapy', 'FlipboardRSS', 'Amazonbot',
#                           'Needle', 'Diffbot']

# Директории с фикстурами для тестов
FIXTURE_DIRS = []

# Настройки REST
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )

}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=14),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s '
                      '%(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'belfoot_fantasy.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True
        },
    }
}

#//TODO АДМИНКА!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!