name: Testing CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        cd ..
        ls        
        pip install -r requirements.txt

    - name: Create virtual environment
      run: |
        cd belfoot_fantasy/belfoot_fantasy
        touch env.py
        echo "import os" >> env.py
        echo "def set_env():" >> env.py
        echo "  os.environ['SECRET_KEY'] = 'django-insecure-+&!)jq^(5f64m+=$yg9c79v_b)wa2=#$8&16v7e58op_5wwrmb'" >> env.py
        echo "  os.environ['NAME'] = 'belfoot_fantasy_1_db'" >> env.py
        echo "  os.environ['USER'] = 'belfoot_root_1'" >> env.py
        echo "  os.environ['PASSWORD'] = "AhGhjIUHihiHH131HJHjhs*aDadx/Gcvmn#@%!#"" >> env.py
        echo "  os.environ['HOST'] = '127.0.0.1'" >> env.py
        echo "  os.environ['PORT'] = '5432'" >> env.py
        
    - name: Run Tests
      run: |
        cd belfoot_fantasy/apps/databases
        pytest -v tests.py


